### ISSUE TITLE
lxinput doesn't work with e.g. German language setting (locale)

### ISSUE THREAD

**Issue by gchriz** [raspberrypi-ui/lxinput#6]
If the system is configured to use a language with decimal comma instead of decimal point (eg. German) lxinput creates a desktop file formatted with the locale in mind but fails reading it in again here:

```
void read_mouse_speed (void)
...
    FILE *fp = popen ("grep -Po \"Accel Speed\\\" [-.0-9]*\" ~/.config/autostart/LXinput-setup.desktop | head -1 | cut -f 3 -d ' '", "r");
```
In that line the decimal point is hard coded. Adding a comma in [-.0-9] makes it work:

```
    FILE *fp = popen ("grep -Po \"Accel Speed\\\" [-.,0-9]*\" ~/.config/autostart/LXinput-setup.desktop | head -1 | cut -f 3 -d ' '", "r");
```
So the mouse speed is reset to default on every call of lxinput.

**Comment by spl237** [comment]
Well spotted! I'll add your fix in the next couple of days and get a new version out - many thanks for that.

**Comment by gchriz** [comment]
I think my "fix" is a workaround only. 

To have a correct _.config/autostart/LXinput-setup.desktop_  it might be a good idea to fix the creation of the desktop file in the first place.

As far as I can tell _xinput_ requires the Accel Speed to be in English format: with decimal **point**.

A fix might go here, in main() (twice):

`mstr = g_strdup_printf ("; xinput --set-prop \"pointer:%s\" \"libinput Accel Speed\" %f", l->data, facc);`

Unfortunately I don't know C and GTK well enough to provide the fixed command writing facc as decimal **point** value regardless of the language settings.

Always:

`Exec=sh -c 'xset m 20/10 10 r rate 500 33 b on; xinput --set-prop "pointer:PixArt USB Optical Mouse" "libinput Accel Speed" 0.960000'`

Instead of (e.g. with German locale):

`Exec=sh -c 'xset m 20/10 10 r rate 500 33 b on; xinput --set-prop "pointer:PixArt USB Optical Mouse" "libinput Accel Speed" 0,960000'` 

Hopefully I was able to describe it...

**Comment by spl237** [comment]
This should now be fixed as per your other suggestion - reading directly from xinput.

**Comment by gchriz** [comment]
Thanks! 
Unfortunately it's not fixed completely. 

lxinput now reads directly from xinput but still creates a wrong entry in _.config/autostart/LXinput-setup.desktop_
That entry (the floating point value) is still formatted in locale's (here German) format and thus wrong.

As that saved command gets executed when lxinput starts, the accel speed is reset to 0 every time.

IMHO  in main() _mstr_ could/should be always empty  - or removed completely. If lxinput reads from xinput the entry in LXinput-setup.desktop isn't needed any more.

If it **is** needed, it has to be in LANG=C format regardless of the users locale setting as described above.

**Comment by spl237** [comment]
OK, this is seriously broken - something in bullseye has changed which is causing problems. It's not just the localisation - even with that sorted, the config in the autostart is not loading consistently. That autostart is required because the mouse speed is not handled by the xsettings daemon, and needs to be manually set at startup, but the script which should be doing that is failing for reasons I don't understand as yet; I have a suspicion something elsewhere is overwriting what it does. I'm investigating at the moment.

**Comment by spl237** [comment]
OK, mutter is just ignoring settings in that file and using a speed setting stored in (yet) another place; I'll need to modify lxinput to update that as well. The fact that the Linux desktop environment now has three different places where you need to set the mouse speed is not a sign that it was designed all that well...

**Comment by spl237** [comment]
OK, I've done a lot of rewriting today and fixed a whole pile of issues. The app now works correctly for me in both English and German locales, under both openbox and mutter. The new version should be in apt within the next day or so - I'll close this for now, but if you find anything which still isn't fixed, feel free to reopen and report back.

**Comment by gchriz** [comment]
This afternoon I finally was able to compile lxinput locally. (I'm a rookie regarding compiler languages.)

So I tried your current commit now with a quick test.
It seems to be working as expected!  :-))  

I'll test the official (apt) version as soon as it arrives and let you know the results.

**Comment by gchriz** [comment]
The update for RaspiOS Bullseye arrived here today. 
I **successfully** tested lxinput on a Pi400 with German locale! Thanks!

When it's available for Buster too I'll test there as well.

**Comment by spl237** [comment]
Glad it worked - thanks for testing.

This change probably won't be ported to buster - that is now a frozen release which will only get security-related patches. But if you want the change on there, you can rebuild the code from GitHub - it should work fine.

**Comment by gchriz** [comment]
Then we could close this one.
